### **IMPORT LIBRARY**

In [45]:
import pandas as pd
import numpy as np

### **PEMBACAAN DATA**

In [46]:
df = pd.read_csv("C:/Users/visco/IF-UNDIP/SEM 2/Statistika/LK2/Latihan.csv")

### **Properti #1:**

Menambah atau mengurangi dengan suatu nilai konstanta untuk semua dataset. Untuk menemukan properti pertama, kita akan mencari nilai mean (rata-rata) dan median (nilai tengah) dari kumpulan data, lalu menambahkan (atau mengurangi) suatu nilai konstanta yang sama untuk setiap baris dalam data, dan menemukan nilai rata-rata dan median yang baru.

**Langkah 1:**

Hitung nilai standard deviation dan variance sebelum memodifikasi dataset untuk
variabel Tipe3

In [47]:
df.head()

   Tipe1  Tipe2  Tipe3  Tipe4
0      5      5      4      2
1      5      3      2      3
2      5      4      2      3
3      5      3      2      2
4      4      3      2      4

In [48]:
#SEBELUM

print('=== Sebelum ===')
std_before = df['Tipe3'].std()
var_before = df['Tipe3'].var()
print(f'Standar deviasi Tipe3   : {std_before}')
print(f'Variansi Tipe3          : {var_before}')

=== Sebelum ===
Standar deviasi Tipe3   : 3.9046675366064867
Variansi Tipe3          : 15.24642857142857

**Langkah 2:**

Modifikasi satu buah variabel dari dataset terkait dengan menambahkan atau
mengurangi suatu konstanta untuk setiap data.

In [49]:
#SETELAH ditambah Konstanta
df['Tipe3'] -= 8
df.head()

   Tipe1  Tipe2  Tipe3  Tipe4
0      5      5     -4      2
1      5      3     -6      3
2      5      4     -6      3
3      5      3     -6      2
4      4      3     -6      4

**Langkah 3:**

Hitung nilai standard deviation dan variance dari modified dataset untuk melengkapi tabel pada Langkah 1 dan lakukan analisa terhadap hasil yang diperoleh sesuai pertanyaan berikut ini.

In [50]:
print('=== Setelah ===')
std_after = df['Tipe3'].std()
var_after = df['Tipe3'].var()
print(f'Standar Deviasi Tipe3   : {std_after}')
print(f'Variansi Tipe3          : {var_after}')

=== Setelah ===
Standar Deviasi Tipe3   : 3.9046675366064867
Variansi Tipe3          : 15.24642857142857

Setelah dilakukan penambahan konstanta pada seluruh data, diperoleh bahwa nilai standar deviasi dan variansi tidak mengalami perubahan. Hal ini terjadi karena penambahan konstanta hanya menggeser seluruh data tanpa mengubah jarak relatif antar data terhadap nilai rata-rata.

Dengan demikian, dapat disimpulkan bahwa variansi dan standar deviasi bersifat invariant (tidak berubah) terhadap penjumlahan atau pengurangan konstanta.

### **Properti #2:**

Mengalikan atau membagi dengan suatu nilai konstanta untuk semua dataset.

**Langkah 1:**

Hitung nilai standard deviation dan variance sebelum memodifikasi dataset untuk
variabel Tipe2

In [51]:
df.head()

   Tipe1  Tipe2  Tipe3  Tipe4
0      5      5     -4      2
1      5      3     -6      3
2      5      4     -6      3
3      5      3     -6      2
4      4      3     -6      4

In [52]:
#SEBELUM
print('=== Sebelum ===')
std_before = df['Tipe2'].std()
var_before = df['Tipe2'].var()
print(f'Standar Deviasi Tipe2   : {std_before}')
print(f'Variasi Tipe2           : {var_before}')

=== Sebelum ===
Standar Deviasi Tipe2   : 3.8048158137580557
Variasi Tipe2           : 14.476623376623376

**Langkah 2:**

Modifikasi satu buah variabel dari dataset terkait dengan menambahkan suatu
konstanta untuk setiap data.

In [53]:
#SETELAH ditambah Konstanta
df['Tipe2'] *= -4

df.head()

   Tipe1  Tipe2  Tipe3  Tipe4
0      5    -20     -4      2
1      5    -12     -6      3
2      5    -16     -6      3
3      5    -12     -6      2
4      4    -12     -6      4

**Langkah 3:**

Hitung nilai standard deviation dan variance dari modified dataset untuk
melengkapi tabel pada Langkah 1 dan lakukan analisa terhadap hasil yang diperoleh sesuai
pertanyaan berikut ini.

In [54]:
print('=== Setelah ===')
std_after = df['Tipe2'].std()
var_after = df['Tipe2'].var()
print(f'Standar Deviasi Tipe2   : {std_after}')
print(f'Variansi Tipe2          : {var_after}')

=== Setelah ===
Standar Deviasi Tipe2   : 15.219263255032223
Variansi Tipe2          : 231.62597402597402

Setelah seluruh data dikalikan dengan suatu konstanta, nilai variansi berubah menjadi sebesar kuadrat dari konstanta tersebut dikalikan dengan variansi awal, sedangkan standar deviasi berubah menjadi sebesar nilai absolut konstanta dikalikan dengan standar deviasi awal.

Dengan demikian, dapat disimpulkan bahwa variansi bersifat kuadratik terhadap konstanta, sedangkan standar deviasi bersifat linear terhadap konstanta.

### **Properti #3:**

Sensitif terhadap Outliers

**Langkah 1:**

Hitung nilai standard deviation dan variance sebelum memodifikasi dataset untuk
variabel Tipe4

In [55]:
df.head()

   Tipe1  Tipe2  Tipe3  Tipe4
0      5    -20     -4      2
1      5    -12     -6      3
2      5    -16     -6      3
3      5    -12     -6      2
4      4    -12     -6      4

In [56]:
#SEBELUM
print('=== Sebelum ===')
std_before = df['Tipe4'].std()
var_before = df['Tipe4'].var()
print(f'Standar Deviasi Tipe4   : {std_before}')
print(f'Variasi Tipe4           : {var_before}')

=== Sebelum ===
Standar Deviasi Tipe4   : 1.869439807751294
Variasi Tipe4           : 3.4948051948051946

**Langkah 2:**

Modifikasi dataset dengan menambahkan satu baris data.

In [57]:
# Tambah satu baris dengan nilai 1000
new_row = {'Tipe4': 1000}

df = pd.concat([df, pd.DataFrame([new_row])], ignore_index=True)

df.tail()

    Tipe1  Tipe2  Tipe3  Tipe4
52   15.0  -40.0    0.0      2
53    4.0  -80.0    4.0      5
54   15.0  -24.0   -3.0      4
55   20.0  -20.0   -5.0      6
56    NaN    NaN    NaN   1000

**Langkah 3:**

Hitung nilai standard deviation dan variance dari modified dataset untuk
melengkapi tabel pada Langkah 1 dan lakukan analisa terhadap hasil yang diperoleh sesuai
pertanyaan berikut ini.

In [58]:
print('=== Setelah ===')
std_after = df['Tipe4'].std()
var_after = df['Tipe4'].var()
print(f'Standar Deviasi Tipe4   : {std_after}')
print(f'Variansi Tipe4          : {var_after}')

=== Setelah ===
Standar Deviasi Tipe4   : 131.97900123473164
Variansi Tipe4          : 17418.456766917294

Penambahan satu data ekstrem (1000) menyebabkan nilai standar deviasi dan variansi meningkat signifikan karena keduanya mengukur penyebaran data terhadap rata-rata. Nilai yang jauh dari mean menghasilkan selisih yang besar, dan pada variansi selisih tersebut dikuadratkan sehingga efeknya semakin besar. Akibatnya, standar deviasi juga ikut meningkat. Dengan demikian, variansi dan standar deviasi sangat sensitif terhadap outlier.